### ISSUE TITLE
ModuleNotFoundError: No module named 'optunahub_registry.package'; 'optunahub_registry' is not a package

### ISSUE THREAD

**Issue by raphaelxjy** [optuna/optunahub#66]
I have a structure where I have two layers of studies, and each evaluation of the outer objective function creates a new inner study. When I try to use a sampler from a loaded module from optunahub as the sampler for my inner study, I get a ModuleNotFoundError. There's no issue when I use the same optunahub module sampler for my outer study, it's only when I use it for the inner one. The entire setup works fine when working with the default TPESampler() for both the inner/outer studies.

The creation of the inner study and the calling of optimize are defined in a separate python file, and not the main Jupyter notebook which everything is being executed in. Before importing optunahub in that file, the error was ModuleNotFoundError: No module named 'optunahub_registry'. After importing, the error appeared as shown in the title. Not sure if that helps diagnose the issue.

Would appreciate any help/guidance! Thanks in advance.

**Comment by y0z** [comment]
Thank you for your report.
Based on your description, I tried reproducing your issue but couldn't.
If you use an older optunahub version, please upgrade it first.

For example, the following code works fine.
```python
import optuna
import optunahub


def inner_objective(trial):
    x = trial.suggest_float("x", 0, 1)
    return x


def outer_objective(trial):
    x = trial.suggest_float("x", 0, 1)

    study = optuna.create_study()
    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    study.optimize(inner_objective, n_trials=10)
    return x + study.best_value


if __name__ == "__main__":
    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    study.optimize(outer_objective, n_trials=10)
```

**Comment by raphaelxjy** [comment]
Thank you for the help! I looked into it more and managed to replicate the issue I was facing: I believe it only appears when parallelisation is being conducted via joblib. I've attached the code below.



```
import optuna
import optunahub
from joblib import Parallel, delayed


def inner_objective(trial):
    x = trial.suggest_float("x", 0, 1)
    return x

def outer_objective(trial):
    x = trial.suggest_float("x", 0, 1)

    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    study.optimize(inner_objective, n_trials=10)
    return x + study.best_value

def optimize(n_trials):
    study = optuna.create_study(sampler=sampler)
    study.optimize(outer_objective, n_trials=n_trials)

if __name__ == "__main__":
    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    r = Parallel(n_jobs=-1)([delayed(optimize)(2) for _ in range(2)])
```

**Comment by y0z** [comment]
As a workaround, how about loading the sampler inside `optimize`?

```python
import optuna
import optunahub
from joblib import Parallel, delayed


def inner_objective(trial):
    x = trial.suggest_float("x", 0, 1)
    return x

def outer_objective(trial):
    x = trial.suggest_float("x", 0, 1)

    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    study.optimize(inner_objective, n_trials=10)
    return x + study.best_value

def optimize(n_trials):
    sampler = optunahub.load_module("samplers/simulated_annealing").SimulatedAnnealingSampler()
    study = optuna.create_study(sampler=sampler)
    study.optimize(outer_objective, n_trials=n_trials)

if __name__ == "__main__":
    r = Parallel(n_jobs=-1)([delayed(optimize)(2) for _ in range(2)])
```

**Comment by raphaelxjy** [comment]
that works! thank you for your help.
